### ISSUE TITLE
[Bug] Firebot is unable to connect to chat

### ISSUE THREAD

**Issue by julben** [crowbartools/Firebot#1231]
- Describe the bug:
Firebot cannot connect to Twitch chat (see log below).

- Steps To Reproduce:
1. Follow the quick initial setup to login to your Twitch account.
2. Allow Firebot to manage your Twitch account
3. The error can be seen in the standard output or by the fact that hovering on the Twitch icon displays "Twitch: Disconnected".

- Expected behavior:
Firebot to have access to the Twitch chat. I should add that, while the initial setup went fine (except for the overlay shows no connection while integrated into OBS studio, displaying inside it a black screen).

- Firebot Version: 5.39.2

- Computer OS: Linux (Debian 11 Bullseye/testing)

- standard output (extract):
`info: Connecting to Twitch PubSub...
debug: ViewerDB: Trying to set all users to offline.
debug: ViewerDB: No users were set to offline.
error: Chat connect error 
{
  message: 'request to https://badges.twitch.tv/v1/badges/channels/47213250/display failed, reason: connect ECONNREFUSED 0.0.0.0:443',
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  stack: 'FetchError: request to https://badges.twitch.tv/v1/badges/channels/47213250/display failed, reason: connect ECONNREFUSED 0.0.0.0:443\n' +
    '    at ClientRequest.<anonymous> (/home/jul/Downloads/firebot-v5.39.2-linux-x64/resources/app.asar/node_modules/@d-fischer/cross-fetch/node_modules/node-fetch/lib/index.js:1461:11)\n' +
    '    at ClientRequest.emit (events.js:203:13)\n' +
    '    at TLSSocket.socketErrorListener (_http_client.js:399:9)\n' +
    '    at TLSSocket.emit (events.js:203:13)\n' +
    '    at emitErrorNT (internal/streams/destroy.js:91:8)\n' +
    '    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:77:11)'
}
debug: ViewerDB: Trying to set all users to offline.
debug: ViewerDB: Trying to set all users to offline.
debug: ViewerDB: No users were set to offline.
debug: ViewerDB: No users were set to offline.
info: Connected to the Twitch PubSub!
debug: ViewerDB: Compaction should be happening now. Compaction Interval: 30000
debug: Running currency timer...
debug: ViewerDB: Setting last seen date for 0 users
debug: ViewerDB: Compaction should be happening now. Compaction Interval: 30000
`

[2021-06-26.log](https://github.com/crowbartools/Firebot/files/6719629/2021-06-26.log)

**Comment by julben** [comment]
I finally figured it was because of my ad-blocking system on my network. Closing this issue.
