### ISSUE TITLE
[Bug] In release v5.47.0 counters are broken

### ISSUE THREAD

**Issue by Roger** [crowbartools/Firebot#1473]
**Describe the bug**
Running an update counter effect fails writing the counter to disk, looks like is related to the updated dependencies, since I don't see any change in the handling of writes

Traceback:
```
error: There was an error running effect of type firebot:update-counter with id 4a28ec70-bc9f-11eb-9939-8f432616befc
{
  message: 'The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (274)',
  stack: 'TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (274)\n' +
    '    at writeFile (fs.js:1436:5)\n' +
    '    at go$writeFile (/home/roger/Downloads/fire/resources/app.asar/node_modules/graceful-fs/graceful-fs.js:106:14)\n' +
    '    at Object.writeFile (/home/roger/Downloads/fire/resources/app.asar/node_modules/graceful-fs/graceful-fs.js:103:12)\n' +
    '    at /home/roger/Downloads/fire/resources/app.asar/node_modules/universalify/index.js:13:12\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at Object.writeFile (/home/roger/Downloads/fire/resources/app.asar/node_modules/universalify/index.js:7:14)\n' +
    '    at updateCounterTxtFile (/home/roger/Downloads/fire/resources/app.asar/backend/counters/counter-manager.js:41:15)\n' +
    '    at Object.updateCounterValue (/home/roger/Downloads/fire/resources/app.asar/backend/counters/counter-manager.js:158:11)\n' +
    '    at Object.onTriggerEvent (/home/roger/Downloads/fire/resources/app.asar/backend/effects/builtin/update-counter.js:93:30)\n' +
    '    at triggerEffect (/home/roger/Downloads/fire/resources/app.asar/backend/common/effect-runner.js:89:22)',
  code: 'ERR_INVALID_ARG_TYPE'
```

**Steps To Reproduce**
Create a counter and use an effect to update it

**Expected behavior**
Enter a clear and concise description of what you expected to happen.

**Firebot Version:**
v5.47.0

**Computer OS:**
Archlinux

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by ebiggz** [comment]
This was fixed in v5.47.1. Thanks for the report!
