### ISSUE TITLE
[Bug] Error: Failed to lookup view with Ubuntu 20.04

### ISSUE THREAD

**Issue by liloumuloup** [crowbartools/Firebot#1577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I tried to add Firebot to my OBS Studio overlay, as described in the settings or during the first start of Firebot but i couldn't make it work.

I currently have only an error printed (pasted below).

I'm using the "Direct ink/2 PC Setup", instead of the OBS/Streamlabs Desktop because didn't work either but with an empty window, instead of the error. I created a thread in Discord here with the details related to the empty window  : [Connection between Firebot and OBS Ubuntu 20.04](https://discord.com/channels/372817064034959370/940735444163911710)

Versions : 
* Ubuntu 20.04.3 LTS (64-bit) with Gnome 3.36.8
* OBS Studio 26.0.0 (64bit)
* Firebot-v5.50.3-linux-x64

### Expected Behavior

Have the tests of the alerts printed when i test them.

### Steps To Reproduce

1. Launch both Firebot and OBS Studio
2. Go to settings -> Overlay
3. Get the Overlay URL using "Get Overlay Path" and "Direct ink/2 PC Setup"
4. Go to OBS Studio and add a browser source with the following parameters : 
![image](https://user-images.githubusercontent.com/4968531/153255841-7a677bb1-baae-48dc-b37a-50875ab53813.png)

### Version

5.50.3

### What operating system are you using Firebot on?

Linux Distro

### Relevant log output

```shell
Error: Failed to lookup view "../resources/overlay" in views directory "/home/liloumuloup/views"
    at Function.render (/home/liloumuloup/Documents/Stream/firebot/resources/app.asar/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/home/liloumuloup/Documents/Stream/firebot/resources/app.asar/node_modules/express/lib/response.js:1012:7)
    at /home/liloumuloup/Documents/Stream/firebot/resources/app.asar/server/httpServer.js:82:13
    at Layer.handle [as handle_request] (/home/liloumuloup/Documents/Stream/firebot/resources/app.asar/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/liloumuloup/Documents/Stream/firebot/resources/app.asar/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/liloumuloup/Documents/Stream/firebot/resources/app.asar/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/liloumuloup/Documents/Stream/firebot/resources/app.asar/node_modules/express/lib/router/layer.js:95:5)
    at /home/liloumuloup/Documents/Stream/firebot/resources/app.asar/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/liloumuloup/Documents/Stream/firebot/resources/app.asar/node_modules/express/lib/router/index.js:335:12)
    at next (/home/liloumuloup/Documents/Stream/firebot/resources/app.asar/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/home/liloumuloup/Documents/Stream/firebot/resources/app.asar/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (events.js:315:20)
    at SendStream.error (/home/liloumuloup/Documents/Stream/firebot/resources/app.asar/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/home/liloumuloup/Documents/Stream/firebot/resources/app.asar/node_modules/send/index.js:421:12)
    at next (/home/liloumuloup/Documents/Stream/firebot/resources/app.asar/node_modules/send/index.js:735:16)
    at onstat (/home/liloumuloup/Documents/Stream/firebot/resources/app.asar/node_modules/send/index.js:724:14)
    at FSReqCallback.oncomplete (fs.js:183:21)
```

### Contact Details (Optional)

Liloumuloup#7839

**Comment by liloumuloup** [comment]
Ok ! found a solution ! (Thank you Perry for the help)

I forgot the pathin my Gnome Shortcut.

If it helps someone, my Gnome Shortcut  : 
```
[Desktop Entry]
Name=Firebot
Exec="/home/liloumuloup/Documents/Stream/firebot/Firebot v5"
Path=/home/liloumuloup/Documents/Stream/firebot/
Terminal=false
Type=Application
Icon=/home/liloumuloup/Documents/Stream/firebot/icon.png
Comment=Help Bot from Twitch
Categories=Sound & Video;
```

**Comment by brumoen** [comment]
This was caused by running Firebot via a shortcut without setting the "Start in" /"Execute from" path so it tried to load resources from the wrong directory.

Same error happens on Windows if you make a shortcut for Firebot and set the wrong folder as the "Start in" directory.

**Comment by pdschneider** [comment]
So............... Step by step, how do I fix this? Still having this issue in 2025 on the latest build.
