### ISSUE TITLE
[Bug] Keyboard buttons locked by keyboard shortcuts

### ISSUE THREAD

**Issue by PierreLucDaoust** [crowbartools/Firebot#1682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After configuring some hotkeys in Firebot with the «Shift» modifier, «Shift» gets fully locked by Firebot, even if not using the full hotkey. For example, if I configure a hotkey «Shift + F4», «Shift» is locked completely. It doesn't seem to happen with «Control». If I set a hotkey only with F13-F24, the whole keyboard gets locked. This problem stops when I disable the hotkey.

On Linux Mint 20

### Expected Behavior

Having only the whole hotkey being locked by Firefot. Or having an option to disable this protection, leaving to us the task to make sure there's no conflict.

### Steps To Reproduce

1. Open Firebot
2. Create a hotkey with «Shift» or only with F13-F24 and enable it

### Version

5.51.0

### What operating system are you using Firebot on?

Linux Distro

### Relevant log output

```shell
20:16:35 GMT-0400 (heure avancée de l’Est) - info: [v5.51.0] Starting Firebot...
20:16:35 GMT-0400 (heure avancée de l’Est) - info: [v5.51.0] Ensuring required data folders exist...
20:16:35 GMT-0400 (heure avancée de l’Est) - error: [v5.51.0] Failed to copy resource overlay.html 
{
  message: "ENOENT: no such file or directory, open '/home/pldaoust/resources/overlay.html'",
  stack: "Error: ENOENT: no such file or directory, open '/home/pldaoust/resources/overlay.html'\n" +
    '    at Object.openSync (fs.js:476:3)\n' +
    '    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)\n' +
    '    at Object.readFileSync (fs.js:377:35)\n' +
    '    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8872)\n' +
    '    at Object.copyResourceToUserData (/jeuxvideo/firebot/resources/app.asar/backend/common/data-access.js:159:42)\n' +
    '    at ensureRequiredFoldersExist (/jeuxvideo/firebot/resources/app.asar/backend/app-management/data-tasks.js:25:16)\n' +
    '    at exports.whenReady (/jeuxvideo/firebot/resources/app.asar/backend/app-management/electron/events/when-ready.js:17:5)',
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/pldaoust/resources/overlay.html'
}
20:16:35 GMT-0400 (heure avancée de l’Est) - info: [v5.51.0] Finished verifying required folders exist.
20:16:36 GMT-0400 (heure avancée de l’Est) - info: [v5.51.0] Setting logged in user cache.
20:16:36 GMT-0400 (heure avancée de l’Est) - info: [v5.51.0] Setting up refreshing auth providers...
20:16:36 GMT-0400 (heure avancée de l’Est) - info: [v5.51.0] Successfully setup streamer refreshing auth provider
20:16:36 GMT-0400 (heure avancée de l’Est) - info: [v5.51.0] Unable to setup bot refreshing auth provider as bot account is not logged in.
20:16:36 GMT-0400 (heure avancée de l’Est) - info: [v5.51.0] Finished setting up Twitch API client for streamer account.
20:16:36 GMT-0400 (heure avancée de l’Est) - info: [v5.51.0] Updated Command cache.
20:16:37 GMT-0400 (heure avancée de l’Est) - info: [v5.51.0] Attempting to setup chat moderation worker...
20:16:37 GMT-0400 (heure avancée de l’Est) - info: [v5.51.0] Finished setting up chat moderation worker.
20:16:37 GMT-0400 (heure avancée de l’Est) - info: [v5.51.0] Updated Hotkeys cache.
20:16:37 GMT-0400 (heure avancée de l’Est) - info: [v5.51.0] Creating or connecting user database
20:16:37 GMT-0400 (heure avancée de l’Est) - info: [v5.51.0] ViewerDB: Trying to connect to user database...
20:16:37 GMT-0400 (heure avancée de l’Est) - info: [v5.51.0] ViewerDB: User Database Loaded:  /home/pldaoust/.config/Firebot/v5/profiles/Main Profile/db/users.db
20:16:37 GMT-0400 (heure avancée de l’Est) - info: [v5.51.0] Creating or connecting stats database
20:16:37 GMT-0400 (heure avancée de l’Est) - info: [v5.51.0] Creating or connecting quotes database
20:16:37 GMT-0400 (heure avancée de l’Est) - info: [v5.51.0] Doing once a day backup
20:16:37 GMT-0400 (heure avancée de l’Est) - info: [v5.51.0] Backup manualActivation: false
20:16:38 GMT-0400 (heure avancée de l’Est) - info: [v5.51.0] Web Server listening on port 7472.
20:16:39 GMT-0400 (heure avancée de l’Est) - info: [v5.51.0] got 'get all cmd defs' request
20:16:39 GMT-0400 (heure avancée de l’Est) - info: [v5.51.0] Updated Command cache.
20:16:39 GMT-0400 (heure avancée de l’Est) - info: [v5.51.0] got 'get all integrations' request
20:16:39 GMT-0400 (heure d’été de l’Est) - info: [v5.51.0] Setting logged in user cache.
20:16:46 GMT-0400 (heure avancée de l’Est) - info: [v5.51.0] Connecting to Twitch PubSub...
20:16:47 GMT-0400 (heure avancée de l’Est) - error: [v5.51.0] Failed to get channel bttv emotes: Request failed with status code 404
20:16:48 GMT-0400 (heure avancée de l’Est) - error: [v5.51.0] Failed to get channel 7TV emotes: Request failed with status code 404
20:16:49 GMT-0400 (heure avancée de l’Est) - info: [v5.51.0] Connected to the Twitch PubSub!
20:17:16 GMT-0400 (heure avancée de l’Est) - info: [v5.51.0] Updated Hotkeys cache.
20:17:31 GMT-0400 (heure avancée de l’Est) - info: [v5.51.0] Updated Hotkeys cache.
20:18:43 GMT-0400 (heure d’été de l’Est) - info: [v5.51.0] (Renderer) Starting hotkey capture...
20:18:54 GMT-0400 (heure d’été de l’Est) - info: [v5.51.0] (Renderer) Stopping hotkey recording
20:19:24 GMT-0400 (heure avancée de l’Est) - info: [v5.51.0] Updated Hotkeys cache.
20:20:05 GMT-0400 (heure avancée de l’Est) - info: [v5.51.0] Updated Hotkeys cache.
20:20:16 GMT-0400 (heure d’été de l’Est) - info: [v5.51.0] (Renderer) Starting hotkey capture...
20:20:18 GMT-0400 (heure d’été de l’Est) - info: [v5.51.0] (Renderer) Stopping hotkey recording
20:20:26 GMT-0400 (heure d’été de l’Est) - info: [v5.51.0] (Renderer) Starting hotkey capture...
20:20:28 GMT-0400 (heure d’été de l’Est) - info: [v5.51.0] (Renderer) Stopping hotkey recording
20:20:30 GMT-0400 (heure d’été de l’Est) - info: [v5.51.0] (Renderer) Starting hotkey capture...
20:20:32 GMT-0400 (heure d’été de l’Est) - info: [v5.51.0] (Renderer) Stopping hotkey recording
20:20:35 GMT-0400 (heure d’été de l’Est) - info: [v5.51.0] (Renderer) Starting hotkey capture...
20:20:36 GMT-0400 (heure d’été de l’Est) - info: [v5.51.0] (Renderer) Stopping hotkey recording
20:20:41 GMT-0400 (heure d’été de l’Est) - info: [v5.51.0] (Renderer) Starting hotkey capture...
20:20:42 GMT-0400 (heure d’été de l’Est) - info: [v5.51.0] (Renderer) Stopping hotkey recording
20:20:47 GMT-0400 (heure avancée de l’Est) - info: [v5.51.0] Updated Hotkeys cache.
20:20:49 GMT-0400 (heure d’été de l’Est) - info: [v5.51.0] (Renderer) Starting hotkey capture...
20:20:53 GMT-0400 (heure d’été de l’Est) - info: [v5.51.0] (Renderer) Stopping hotkey recording
20:21:00 GMT-0400 (heure d’été de l’Est) - info: [v5.51.0] (Renderer) Starting hotkey capture...
20:21:02 GMT-0400 (heure d’été de l’Est) - info: [v5.51.0] (Renderer) Stopping hotkey recording
20:21:13 GMT-0400 (heure d’été de l’Est) - info: [v5.51.0] (Renderer) Starting hotkey capture...
20:21:14 GMT-0400 (heure d’été de l’Est) - info: [v5.51.0] (Renderer) Stopping hotkey recording
20:21:18 GMT-0400 (heure avancée de l’Est) - info: [v5.51.0] Updated Hotkeys cache.
20:21:21 GMT-0400 (heure avancée de l’Est) - info: [v5.51.0] Updated Hotkeys cache.
20:21:33 GMT-0400 (heure avancée de l’Est) - info: [v5.51.0] Updated Hotkeys cache.
```

### Contact Details (Optional)

pl@zonepl.net; Discord: Monsieur P-L#4607

**Comment by Firebottle** [comment]
We definitely need to research a new way to handle hotkeys, especially as we move towards multi platform support. I honestly am not sure if this feature even works on linux.
