### ISSUE TITLE
[Bug] While Loops Error 

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#1984]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior
Loop Effects While Condition  with default value throws error 
```
error: Unhandled promise rejection
{
  message: 'effect.loopCount.trim is not a function',
  stack: 'TypeError: effect.loopCount.trim is not a function\n' +
    '    at F:\\fork-firebot\\Firebot\\build\\backend\\effects\\builtin\\loop-effects.js:147:65\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at Object.onTriggerEvent (F:\\fork-firebot\\Firebot\\build\\backend\\effects\\builtin\\loop-effects.js:91:16)\n' +
    '    at triggerEffect (F:\\fork-firebot\\Firebot\\build\\backend\\common\\effect-runner.js:85:22)\n' +
    '    at runEffects (F:\\fork-firebot\\Firebot\\build\\backend\\common\\effect-runner.js:106:36)\n' +
    '    at runMicrotasks (<anonymous>)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:93:5)'
}
```
change the value to anything including the default value and it works 
### Expected Behavior

Please FIX 

### Steps To Reproduce

```
{"id":"2e05b3b0-6bbd-11ed-9c91-f73e9f5a94c3","type":"firebot:loopeffects","active":true,"effectList":{"list":[{"id":"57482410-6bbd-11ed-9c91-f73e9f5a94c3","type":"firebot:chat","active":true,"chatter":"Bot","message":"Im A BOT"}],"id":"2e0f0280-6bbd-11ed-9c91-f73e9f5a94c3"},"loopMode":"conditional","conditionData":{"mode":"exclusive","conditions":[{"type":"firebot:custom","comparisonType":"is","value":null,"leftSideValue":"$customVariable[keyObject]"}]},"loopCount":25}
```

### Version

5.54.3

### What operating system are you using Firebot on?

Windows 10

**Comment by CKY-** [comment]
Was checking on this  and i recall it being an error, in the current nightly it seems to have been resolved. I will keep an eye on it and close it if that is the case.
