### ISSUE TITLE
[Support] Firebot 5.57 update, Streamer login fail

### ISSUE THREAD

**Issue by IanBigfoot** [crowbartools/Firebot#2103]
**Help Request**
Enter a clear and concise explanation of the issue you are having or the thing you would like help with.
Firebot updated tonight to 5.57, and it needs to re-auth my streamer and bot accounts. I click on Login under Streamer and nothing happens. Its just a button to click on. I click on the Login button under Bot and the box for the login URL comes up and I can log in. Streamer login still doesn't do anything. I uninstalled, reinstalled, same thing. I installed 5.52 and it automatically updated, and same issue.

Any ideas??

**Comment by zunderscore** [comment]
Would you mind creating a new thread in the #issues channel of our [Discord](https://discord.gg/tTmMbrG)? That would be the fastest route for getting support.

**Comment by zunderscore** [comment]
Is this still an issue? If not, I'll go ahead and close it.

**Comment by Wissididom** [comment]
I think it still is. When I tested the DevTools thingy I had the same problem and thought it was just because I haven't used Firebot in a while. Here is the log my Firebot produced:

```
2023-12-09 15:25:57.0406 - info: [v5.59.0] Starting Firebot...
2023-12-09 15:25:57.0766 - info: [v5.59.0] Ensuring required data folders exist...
2023-12-09 15:25:57.0768 - info: [v5.59.0] Finished verifying required folders exist.
2023-12-09 15:25:57.0804 - info: [v5.59.0] Setting logged in user cache.
2023-12-09 15:25:58.0063 - info: [v5.59.0] Finished setting up Twitch API client
2023-12-09 15:25:58.0220 - info: [v5.59.0] Updated Command cache.
2023-12-09 15:25:58.0347 - info: [v5.59.0] Starting scheduled task manager...
2023-12-09 15:25:58.0348 - info: [v5.59.0] Found 0 scheduled task(s)
2023-12-09 15:25:58.0348 - info: [v5.59.0] Scheduled task manager started
2023-12-09 15:25:59.0136 - warn: [v5.59.0] [accounts.getTwitchData] Failed to get account data: Invalid token supplied
2023-12-09 15:25:59.0666 - info: [v5.59.0] Starting OBS Control...
2023-12-09 15:26:00.0220 - info: [v5.59.0] Attempting to setup chat moderation worker...
2023-12-09 15:26:00.0221 - info: [v5.59.0] Finished setting up chat moderation worker.
2023-12-09 15:26:00.0243 - info: [v5.59.0] Updated Hotkeys cache.
2023-12-09 15:26:00.0244 - info: [v5.59.0] Creating or connecting user database
2023-12-09 15:26:00.0244 - info: [v5.59.0] ViewerDB: Trying to connect to user database...
2023-12-09 15:26:00.0248 - info: [v5.59.0] ViewerDB: User Database Loaded:  /home/dominik/.config/Firebot/v5/profiles/Main Profile/db/users.db
2023-12-09 15:26:00.0248 - info: [v5.59.0] Creating or connecting stats database
2023-12-09 15:26:00.0251 - info: [v5.59.0] Creating or connecting quotes database
2023-12-09 15:26:00.0253 - info: [v5.59.0] Doing once a day backup
2023-12-09 15:26:00.0253 - info: [v5.59.0] Backup manualActivation: false
2023-12-09 15:26:00.0308 - info: [v5.59.0] Ignoring overlay-resources folder
2023-12-09 15:26:00.0323 - info: [v5.59.0] Default web server started, listening on port 7472
2023-12-09 15:26:00.0538 - info: [v5.59.0] deleting old backup: backup_1695752397123_v5.58.0.zip
2023-12-09 15:26:00.0979 - error: [v5.59.0] Unhandled promise rejection 
{
  message: 'Invalid token supplied',
  stack: 'InvalidTokenError: Invalid token supplied',
  cause: {
    _statusCode: 401,
    _url: 'validate',
    _method: 'GET',
    _body: '{\n  "status": 401,\n  "message": "invalid access token"\n}'
  }
}
2023-12-09 15:26:00.0980 - error: [v5.59.0] Error while trying to get streamers broadcast Invalid token supplied
2023-12-09 15:26:01.0171 - error: [v5.59.0] Failed to get teams for broadcaster Invalid token supplied
2023-12-09 15:26:01.0493 - info: [v5.59.0] Setting logged in user cache.
2023-12-09 15:26:01.0737 - info: [v5.59.0] got 'get all cmd defs' request
2023-12-09 15:26:01.0739 - info: [v5.59.0] Updated Command cache.
2023-12-09 15:26:01.0739 - info: [v5.59.0] got 'get all integrations' request
2023-12-09 15:26:02.0768 - info: [v5.59.0] [Firebot Raid Chat Alert] EventSub connection established!
2023-12-09 15:26:02.0771 - info: [v5.59.0] [Firebot Raid Chat Alert] session_welcome: {"metadata":{"message_id":"8ba3687e-1a39-49ba-b9b5-a4ba210ad7e6","message_type":"session_welcome","message_timestamp":"2023-12-09T15:26:02.664503249Z"},"payload":{"session":{"id":"AgoQEu_VzC3sQTG1aK586ZWm-xIGY2VsbC1j","status":"connected","connected_at":"2023-12-09T15:26:02.653207599Z","keepalive_timeout_seconds":10,"reconnect_url":null}}}
2023-12-09 15:26:03.0002 - error: [v5.59.0]  
{ error: 'Unauthorized', status: 401, message: 'Invalid OAuth token' }
2023-12-09 15:26:03.0003 - error: [v5.59.0] 401
2023-12-09 15:26:03.0003 - error: [v5.59.0] Object [AxiosHeaders] {
  connection: 'close',
  'content-length': '69',
  'content-type': 'application/json; charset=utf-8',
  'timing-allow-origin': 'https://www.twitch.tv',
  date: 'Sat, 09 Dec 2023 15:26:02 GMT',
  'x-served-by': 'cache-bfi-krnt7300099-BFI, cache-fra-eddf8230128-FRA',
  'x-cache': 'MISS, MISS',
  'x-cache-hits': '0, 0',
  'x-timer': 'S1702135563.841704,VS0,VS0,VE153',
  vary: 'Accept-Encoding, Origin',
  'strict-transport-security': 'max-age=300'
}
2023-12-09 15:26:04.0848 - info: [v5.59.0] Connecting to Twitch PubSub...
2023-12-09 15:26:04.0850 - info: [v5.59.0] Connected to the Twitch PubSub!
2023-12-09 15:26:05.0441 - error: [v5.59.0] Failed to get channel chat badges 
{
  message: 'Invalid token supplied',
  stack: 'InvalidTokenError: Invalid token supplied',
  cause: {
    _statusCode: 401,
    _url: 'validate',
    _method: 'GET',
    _body: '{\n  "status": 401,\n  "message": "invalid access token"\n}'
  }
}
2023-12-09 15:26:06.0036 - error: [v5.59.0] Failed to get Twitch chat emotes 
{
  message: 'Invalid token supplied',
  stack: 'InvalidTokenError: Invalid token supplied',
  cause: {
    _statusCode: 401,
    _url: 'validate',
    _method: 'GET',
    _body: '{\n  "status": 401,\n  "message": "invalid access token"\n}'
  }
}
2023-12-09 15:26:06.0225 - error: [v5.59.0] Error getting chatter list Invalid token supplied
2023-12-09 15:26:06.0229 - error: [v5.59.0] Failed to connect to chat 
{
  message: 'Invalid token supplied',
  stack: 'InvalidTokenError: Invalid token supplied',
  cause: {
    _statusCode: 401,
    _url: 'validate',
    _method: 'GET',
    _body: '{\n  "status": 401,\n  "message": "invalid access token"\n}'
  }
}
2023-12-09 15:26:06.0231 - warn: [v5.59.0] (Renderer) Unable to connect to chat. Reason: "Invalid token supplied". Try signing out and back into your streamer/bot account(s).
2023-12-09 15:26:06.0251 - error: [v5.59.0] Unhandled promise rejection 
{
  message: 'Invalid token supplied',
  stack: 'InvalidTokenError: Invalid token supplied',
  cause: {
    _statusCode: 401,
    _url: 'validate',
    _method: 'GET',
    _body: '{\n  "status": 401,\n  "message": "invalid access token"\n}'
  }
}
2023-12-09 15:26:06.0890 - error: [v5.59.0] Failed to get global 7TV emotes: getaddrinfo ENOTFOUND api.7tv.app
2023-12-09 15:26:06.0915 - error: [v5.59.0] Failed to get channel 7TV emotes: getaddrinfo ENOTFOUND api.7tv.app
2023-12-09 15:26:06.0915 - error: [v5.59.0] Chat connect error 
{
  message: "Cannot read properties of null (reading 'onAnnouncement')",
  stack: "TypeError: Cannot read properties of null (reading 'onAnnouncement')\n" +
    '    at exports.setupChatListeners (/home/dominik/Firebot/firebot-v5.59.0-linux-x64/resources/app.asar/build/backend/chat/chat-listeners/twitch-chat-listeners.js:23:24)\n' +
    '    at TwitchChat.connect (/home/dominik/Firebot/firebot-v5.59.0-linux-x64/resources/app.asar/build/backend/chat/twitch-chat.js:126:45)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
2023-12-09 15:26:12.0679 - info: [v5.59.0] [Firebot Raid Chat Alert] session_keepalive: {"metadata":{"message_id":"44925541-e6d8-4508-88cf-4b467432557f","message_type":"session_keepalive","message_timestamp":"2023-12-09T15:26:12.664588289Z"},"payload":{}}
2023-12-09 15:26:12.0912 - info: [v5.59.0] [Firebot Raid Chat Alert] EventSub connection closed! (Code: 4003; Reason: connection unused)
2023-12-09 15:26:16.0089 - error: [v5.59.0] Unhandled promise rejection 
{
  message: 'Invalid token supplied',
  stack: 'InvalidTokenError: Invalid token supplied',
  cause: {
    _statusCode: 401,
    _url: 'validate',
    _method: 'GET',
    _body: '{\n  "status": 401,\n  "message": "invalid access token"\n}'
  }
}
2023-12-09 15:26:16.0124 - info: [v5.59.0] (Renderer) Couldnt get streamer data for profile Main Profile while updating the UI. Its possible this account hasnt logged in yet.
2023-12-09 15:26:17.0261 - info: [v5.59.0] API Request from: localhost:7472, for path: /api/v1/auth?providerId=twitch%3Astreamer-account
2023-12-09 15:26:17.0261 - info: [v5.59.0] Redirecting to provider auth uri: https://id.twitch.tv/oauth2/authorize?client_id=[redacted]&redirect_uri=http%3A%2F%2Flocalhost%3A7472%2Fapi%2Fv1%2Fauth%2Fcallback&response_type=token&state=twitch%3Astreamer-account&scope=[scopes]
2023-12-09 15:26:18.0903 - info: [v5.59.0] API Request from: localhost:7472, for path: /api/v1/auth/callback
2023-12-09 15:26:19.0368 - info: [v5.59.0] API Request from: localhost:7472, for path: /api/v1/auth/callback2?access_token=[redacted]&scope=[scopes]&state=twitch%3Astreamer-account&token_type=bearer&
2023-12-09 15:26:19.0369 - info: [v5.59.0] Received token from provider id 'twitch:streamer-account'
2023-12-09 15:26:19.0629 - info: [v5.59.0] Finished setting up Twitch API client
2023-12-09 15:26:26.0566 - info: [v5.59.0] Disconnected from PubSub.
2023-12-09 15:26:26.0566 - info: [v5.59.0] Connecting to Twitch PubSub...
2023-12-09 15:26:26.0566 - info: [v5.59.0] Connected to the Twitch PubSub!
2023-12-09 15:26:29.0143 - error: [v5.59.0] Failed to get global 7TV emotes: getaddrinfo ENOTFOUND api.7tv.app
2023-12-09 15:26:29.0172 - error: [v5.59.0] Failed to get channel 7TV emotes: getaddrinfo ENOTFOUND api.7tv.app
2023-12-09 15:26:40.0879 - info: [v5.59.0] Stopping scheduled task manager...
2023-12-09 15:26:40.0879 - info: [v5.59.0] Scheduled task manager stopped
2023-12-09 15:26:40.0885 - info: [v5.59.0] Backup manualActivation: false
2023-12-09 15:26:40.0886 - info: [v5.59.0] Ignoring overlay-resources folder
2023-12-09 15:26:40.0983 - info: [v5.59.0] deleting old backup: backup_1695752462062_v5.58.0.zip
```

Ignore the `Firebot Raid Chat Alert`. That is a self written extension because I didn't find an Effect for outgoing Raids. I have redacted the access token and the scopes from the logs.

**Comment by zunderscore** [comment]
@Wissididom This appears to be a separate issue. Please log out and back into your streamer account, then restart Firebot. If you continue to experience issues, please create a thread in the issues channel of our Discord.

As for the original issue, closing this as completed. There are upcoming auth changes that should help resolve future issues of this nature.
