### ISSUE TITLE
[Bug] Variable autocomplete for $converttoJSON is listed as "$convertToJSON", resulting in unknown variable errors when using it

### ISSUE THREAD

**Issue by TheBlackParrot** [crowbartools/Firebot#2121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to add a "$convertToJSON" variable from the variable search, but using that with its case as defined in the search box results in unknown variable errors.

### Expected Behavior

It should add a $converttoJSON variable, as this is the case it's actually using.

### Steps To Reproduce

1. Open an effect list
2. Add any effect with text output
3. Search for "convert", select "$convertToJSON"
4. Give it a raw value, save

### Version

5.57.0

### What operating system are you using Firebot on?

Linux Distro

### Relevant log output

```shell
debug: got 'validateVariables' request
debug: Found variable error when validating
{
  message: 'unknown variable',
  stack: 'Error: unknown variable\n' +
    '    at VariableToken.evaluate (/home/theblackparrot/bin/firebot/resources/app.asar/node_modules/expressionish/src/tokens/variable.js:21:19)\n' +
    '    at evaluate (/home/theblackparrot/bin/firebot/resources/app.asar/node_modules/expressionish/src/evaluate.js:50:39)\n' +
    '    at ReplaceVariableManager.findAndValidateVariables (/home/theblackparrot/bin/firebot/resources/app.asar/build/backend/variables/replace-variable-manager.js:88:31)\n' +
    '    at Object.callback (/home/theblackparrot/bin/firebot/resources/app.asar/build/backend/variables/replace-variable-manager.js:170:32)\n' +
    '    at IpcMainImpl.<anonymous> (/home/theblackparrot/bin/firebot/resources/app.asar/build/backend/common/frontend-communicator.js:16:30)\n' +
    '    at IpcMainImpl.emit (events.js:315:20)\n' +
    '    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)\n' +
    '    at Object.emit (events.js:315:20)',
  position: 1,
  varname: 'convertToJSON',
  dataField: 'text',
  rawText: '$convertToJSON[$rawTopMetadata[throws]]'
}
```

### Contact Details (Optional)

TheBlackParrot#5285

**Comment by zunderscore** [comment]
This is a known issue that will be resolved in the next release.
