### ISSUE TITLE
[Bug] Double {user} in command cooldown

### ISSUE THREAD

**Issue by TOWUK** [crowbartools/Firebot#2173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/crowbartools/Firebot/assets/28830162/f308adb8-5280-4d2e-8c3b-a08faac1cdcd)

### Expected Behavior

one used username
![image](https://github.com/crowbartools/Firebot/assets/28830162/8790e62d-8d54-4881-bdb7-8db37c7d6dbb)

### Steps To Reproduce

just create command and add user coldown custom text

### Version

latest

### What operating system are you using Firebot on?

Windows 11

### Relevant log output

```shell
2023-05-31 18:15:49.0206 - info: [v5.57.0] Updated Command cache.
2023-05-31 18:15:59.0705 - error: [v5.57.0] (Renderer) Error: [$rootScope:inprog] $apply already in progress
https://errors.angularjs.org/1.8.3/$rootScope/inprog?p0=%24apply
    at C:\Users\towuk\AppData\Local\firebot\app-5.57.0\resources\app.asar\node_modules\angular\angular.js:138:12
    at beginPhase (C:\Users\towuk\AppData\Local\firebot\app-5.57.0\resources\app.asar\node_modules\angular\angular.js:19888:15)
    at Scope.$apply (C:\Users\towuk\AppData\Local\firebot\app-5.57.0\resources\app.asar\node_modules\angular\angular.js:19620:11)
    at ChildScope.$scope.selectItem (file:///C:/Users/towuk/AppData/Local/firebot/app-5.57.0/resources/app.asar/build/gui/app/directives/chat/chat-autocomplete-menu.component.js:268:28)
    at fn (eval at compile (C:\Users\towuk\AppData\Local\firebot\app-5.57.0\resources\app.asar\node_modules\angular\angular.js:16548:15), <anonymous>:4:228)
    at callback (C:\Users\towuk\AppData\Local\firebot\app-5.57.0\resources\app.asar\node_modules\angular\angular.js:29123:13)
    at ChildScope.$eval (C:\Users\towuk\AppData\Local\firebot\app-5.57.0\resources\app.asar\node_modules\angular\angular.js:19523:28)
    at ChildScope.$apply (C:\Users\towuk\AppData\Local\firebot\app-5.57.0\resources\app.asar\node_modules\angular\angular.js:19622:25)
    at HTMLDivElement.<anonymous> (C:\Users\towuk\AppData\Local\firebot\app-5.57.0\resources\app.asar\node_modules\angular\angular.js:29127:19)
    at HTMLDivElement.dispatch (file:///C:/Users/towuk/AppData/Local/firebot/app-5.57.0/resources/app.asar/build/gui/js/plugins/jquery.min.js:3:10316)
    at HTMLDivElement.q.handle (file:///C:/Users/towuk/AppData/Local/firebot/app-5.57.0/resources/app.asar/build/gui/js/plugins/jquery.min.js:3:8343)
2023-05-31 18:15:59.0706 - error: [v5.57.0] (Renderer) Error: [$rootScope:inprog] $apply already in progress
https://errors.angularjs.org/1.8.3/$rootScope/inprog?p0=%24apply
    at C:\Users\towuk\AppData\Local\firebot\app-5.57.0\resources\app.asar\node_modules\angular\angular.js:138:12
    at beginPhase (C:\Users\towuk\AppData\Local\firebot\app-5.57.0\resources\app.asar\node_modules\angular\angular.js:19888:15)
    at Scope.$digest (C:\Users\towuk\AppData\Local\firebot\app-5.57.0\resources\app.asar\node_modules\angular\angular.js:19218:9)
    at Scope.$apply (C:\Users\towuk\AppData\Local\firebot\app-5.57.0\resources\app.asar\node_modules\angular\angular.js:19630:24)
    at ChildScope.$scope.selectItem (file:///C:/Users/towuk/AppData/Local/firebot/app-5.57.0/resources/app.asar/build/gui/app/directives/chat/chat-autocomplete-menu.component.js:268:28)
    at fn (eval at compile (C:\Users\towuk\AppData\Local\firebot\app-5.57.0\resources\app.asar\node_modules\angular\angular.js:16548:15), <anonymous>:4:228)
    at callback (C:\Users\towuk\AppData\Local\firebot\app-5.57.0\resources\app.asar\node_modules\angular\angular.js:29123:13)
    at ChildScope.$eval (C:\Users\towuk\AppData\Local\firebot\app-5.57.0\resources\app.asar\node_modules\angular\angular.js:19523:28)
    at ChildScope.$apply (C:\Users\towuk\AppData\Local\firebot\app-5.57.0\resources\app.asar\node_modules\angular\angular.js:19622:25)
    at HTMLDivElement.<anonymous> (C:\Users\towuk\AppData\Local\firebot\app-5.57.0\resources\app.asar\node_modules\angular\angular.js:29127:19)
    at HTMLDivElement.dispatch (file:///C:/Users/towuk/AppData/Local/firebot/app-5.57.0/resources/app.asar/build/gui/js/plugins/jquery.min.js:3:10316)
    at HTMLDivElement.q.handle (file:///C:/Users/towuk/AppData/Local/firebot/app-5.57.0/resources/app.asar/build/gui/js/plugins/jquery.min.js:3:8343)
2023-05-31 18:15:59.0706 - error: [v5.57.0] (Renderer) Error: [$rootScope:inprog] $apply already in progress
https://errors.angularjs.org/1.8.3/$rootScope/inprog?p0=%24apply
    at C:\Users\towuk\AppData\Local\firebot\app-5.57.0\resources\app.asar\node_modules\angular\angular.js:138:12
    at beginPhase (C:\Users\towuk\AppData\Local\firebot\app-5.57.0\resources\app.asar\node_modules\angular\angular.js:19888:15)
    at Scope.$digest (C:\Users\towuk\AppData\Local\firebot\app-5.57.0\resources\app.asar\node_modules\angular\angular.js:19218:9)
    at Scope.$apply (C:\Users\towuk\AppData\Local\firebot\app-5.57.0\resources\app.asar\node_modules\angular\angular.js:19630:24)
    at ChildScope.$scope.selectItem (file:///C:/Users/towuk/AppData/Local/firebot/app-5.57.0/resources/app.asar/build/gui/app/directives/chat/chat-autocomplete-menu.component.js:268:28)
    at fn (eval at compile (C:\Users\towuk\AppData\Local\firebot\app-5.57.0\resources\app.asar\node_modules\angular\angular.js:16548:15), <anonymous>:4:228)
    at callback (C:\Users\towuk\AppData\Local\firebot\app-5.57.0\resources\app.asar\node_modules\angular\angular.js:29123:13)
    at ChildScope.$eval (C:\Users\towuk\AppData\Local\firebot\app-5.57.0\resources\app.asar\node_modules\angular\angular.js:19523:28)
    at ChildScope.$apply (C:\Users\towuk\AppData\Local\firebot\app-5.57.0\resources\app.asar\node_modules\angular\angular.js:19622:25)
    at HTMLDivElement.<anonymous> (C:\Users\towuk\AppData\Local\firebot\app-5.57.0\resources\app.asar\node_modules\angular\angular.js:29127:19)
    at HTMLDivElement.dispatch (file:///C:/Users/towuk/AppData/Local/firebot/app-5.57.0/resources/app.asar/build/gui/js/plugins/jquery.min.js:3:10316)
    at HTMLDivElement.q.handle (file:///C:/Users/towuk/AppData/Local/firebot/app-5.57.0/resources/app.asar/build/gui/js/plugins/jquery.min.js:3:8343)
2023-05-31 18:16:06.0045 - info: [v5.57.0] Checking command type... custom
2023-05-31 18:16:06.0045 - info: [v5.57.0] Executing command effects
2023-05-31 18:16:20.0537 - info: [v5.57.0] got 'get all cmd defs' request
2023-05-31 18:16:20.0538 - info: [v5.57.0] Updated Command cache.
2023-05-31 18:16:46.0982 - info: [v5.57.0] got 'get all cmd defs' request
2023-05-31 18:16:46.0983 - info: [v5.57.0] Updated Command cache.
2023-05-31 18:17:06.0467 - info: [v5.57.0] Checking command type... custom
2023-05-31 18:17:06.0467 - info: [v5.57.0] Executing command effects
2023-05-31 18:17:16.0890 - info: [v5.57.0] Checking command type... custom
2023-05-31 18:17:16.0890 - info: [v5.57.0] Executing command effects
2023-05-31 18:17:59.0298 - info: [v5.57.0] got 'get all cmd defs' request
2023-05-31 18:17:59.0299 - info: [v5.57.0] Updated Command cache.
2023-05-31 18:19:21.0087 - info: [v5.57.0] got 'get all cmd defs' request
2023-05-31 18:19:21.0089 - info: [v5.57.0] Updated Command cache.
2023-05-31 18:19:27.0529 - info: [v5.57.0] Checking command type... custom
2023-05-31 18:19:27.0529 - info: [v5.57.0] Executing command effects
2023-05-31 18:19:50.0573 - info: [v5.57.0] got 'get all cmd defs' request
2023-05-31 18:19:50.0574 - info: [v5.57.0] Updated Command cache.
2023-05-31 18:19:51.0973 - info: [v5.57.0] Checking command type... custom
2023-05-31 18:19:51.0973 - info: [v5.57.0] Executing command effects
2023-05-31 18:20:01.0389 - info: [v5.57.0] got 'get all cmd defs' request
2023-05-31 18:20:01.0390 - info: [v5.57.0] Updated Command cache.
2023-05-31 18:20:19.0213 - info: [v5.57.0] got 'get all cmd defs' request
2023-05-31 18:20:19.0214 - info: [v5.57.0] Updated Command cache.
2023-05-31 18:20:20.0316 - info: [v5.57.0] Checking command type... custom
2023-05-31 18:20:20.0316 - info: [v5.57.0] Executing command effects
2023-05-31 18:20:32.0326 - info: [v5.57.0] Checking command type... custom
2023-05-31 18:20:32.0326 - info: [v5.57.0] Executing command effects
2023-05-31 18:21:26.0812 - info: [v5.57.0] got 'get all cmd defs' request
2023-05-31 18:21:26.0813 - info: [v5.57.0] Updated Command cache.
2023-05-31 18:21:27.0634 - info: [v5.57.0] Checking command type... custom
2023-05-31 18:21:27.0634 - info: [v5.57.0] Executing command effects
2023-05-31 18:21:31.0948 - info: [v5.57.0] got 'get all cmd defs' request
2023-05-31 18:21:31.0949 - info: [v5.57.0] Updated Command cache.
2023-05-31 18:21:37.0382 - info: [v5.57.0] Checking command type... custom
2023-05-31 18:21:37.0382 - info: [v5.57.0] Executing command effects
2023-05-31 18:21:45.0323 - info: [v5.57.0] Checking command type... custom
2023-05-31 18:21:45.0323 - info: [v5.57.0] Executing command effects
2023-05-31 18:22:06.0751 - info: [v5.57.0] got 'get all cmd defs' request
2023-05-31 18:22:06.0753 - info: [v5.57.0] Updated Command cache.
2023-05-31 18:22:54.0268 - info: [v5.57.0] got 'get all cmd defs' request
2023-05-31 18:22:54.0269 - info: [v5.57.0] Updated Command cache.
2023-05-31 18:23:02.0512 - info: [v5.57.0] Checking command type... custom
2023-05-31 18:23:02.0512 - info: [v5.57.0] Executing command effects
2023-05-31 18:23:13.0720 - info: [v5.57.0] got 'get all cmd defs' request
2023-05-31 18:23:13.0721 - info: [v5.57.0] Updated Command cache.
2023-05-31 18:23:18.0540 - info: [v5.57.0] got 'get all event sources' request
2023-05-31 18:23:57.0425 - info: [v5.57.0] got 'get all cmd defs' request
2023-05-31 18:23:57.0426 - info: [v5.57.0] Updated Command cache.
2023-05-31 18:25:07.0387 - info: [v5.57.0] got 'get all cmd defs' request
2023-05-31 18:25:07.0389 - info: [v5.57.0] Updated Command cache.
2023-05-31 18:25:11.0338 - info: [v5.57.0] got 'get all cmd defs' request
2023-05-31 18:25:11.0339 - info: [v5.57.0] Updated Command cache.
2023-05-31 18:25:26.0345 - info: [v5.57.0] got 'get all cmd defs' request
2023-05-31 18:25:26.0346 - info: [v5.57.0] Updated Command cache.
2023-05-31 18:25:51.0031 - info: [v5.57.0] got 'get all cmd defs' request
2023-05-31 18:25:51.0033 - info: [v5.57.0] Updated Command cache.
2023-05-31 18:25:52.0060 - info: [v5.57.0] Checking command type... custom
2023-05-31 18:25:52.0060 - info: [v5.57.0] Executing command effects
2023-05-31 18:25:54.0105 - info: [v5.57.0] got 'get all cmd defs' request
2023-05-31 18:25:54.0106 - info: [v5.57.0] Updated Command cache.
2023-05-31 18:25:54.0881 - info: [v5.57.0] Checking command type... custom
2023-05-31 18:25:54.0882 - info: [v5.57.0] Executing command effects
2023-05-31 18:25:59.0977 - info: [v5.57.0] Checking command type... custom
2023-05-31 18:25:59.0977 - info: [v5.57.0] Executing command effects
2023-05-31 18:26:12.0692 - info: [v5.57.0] got 'get all cmd defs' request
2023-05-31 18:26:12.0693 - info: [v5.57.0] Updated Command cache.
2023-05-31 18:26:21.0914 - info: [v5.57.0] got 'get all cmd defs' request
2023-05-31 18:26:21.0915 - info: [v5.57.0] Updated Command cache.
2023-05-31 18:26:26.0443 - info: [v5.57.0] Checking command type... custom
2023-05-31 18:26:26.0443 - info: [v5.57.0] Executing command effects
2023-05-31 18:26:38.0238 - info: [v5.57.0] Checking command type... custom
2023-05-31 18:26:38.0238 - info: [v5.57.0] Executing command effects
2023-05-31 18:27:57.0570 - info: [v5.57.0] got 'get all cmd defs' request
2023-05-31 18:27:57.0571 - info: [v5.57.0] Updated Command cache.
2023-05-31 18:29:01.0104 - info: [v5.57.0] got 'get all cmd defs' request
2023-05-31 18:29:01.0105 - info: [v5.57.0] Updated Command cache.
2023-05-31 18:29:36.0838 - info: [v5.57.0] got 'get all cmd defs' request
2023-05-31 18:29:36.0839 - info: [v5.57.0] Updated Command cache.
2023-05-31 18:31:10.0241 - info: [v5.57.0] got 'get all cmd defs' request
2023-05-31 18:31:10.0242 - info: [v5.57.0] Updated Command cache.
```

### Contact Details (Optional)

TOWUK#3325

**Comment by CKY-** [comment]
Remove {user} from the message
