### ISSUE TITLE
[Bug] Viewers that change their names causing database issues 

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#2198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when a user changes their name firebot trys to create a new user and fails with 
```
2023-03-19 00:06:19.0601 - error: [v5.57.0] ViewerDB: Error adding user 
{
  message: "Can't insert key 409993989, it violates the unique constraint",
  stack: "Error: Can't insert key 409993989, it violates the unique constraint\n" +
    '    at _AVLTree.insert (C:\\Users\\username\\AppData\\Local\\firebotv5\\app-5.57.0\\resources\\app.asar\\node_modules\\binary-search-tree\\lib\\avltree.js:273:19)\n' +
    '    at AVLTree.insert (C:\\Users\\username\\AppData\\Local\\firebotv5\\app-5.57.0\\resources\\app.asar\\node_modules\\binary-search-tree\\lib\\avltree.js:307:27)\n' +
    '    at Index.insert (C:\\Users\\username\\AppData\\Local\\firebotv5\\app-5.57.0\\resources\\app.asar\\node_modules\\nedb\\lib\\indexes.js:77:15)\n' +
    '    at Datastore.addToIndexes (C:\\Users\\username\\AppData\\Local\\firebotv5\\app-5.57.0\\resources\\app.asar\\node_modules\\nedb\\lib\\datastore.js:180:29)\n' +
    '    at Datastore._insertInCache (C:\\Users\\username\\AppData\\Local\\firebotv5\\app-5.57.0\\resources\\app.asar\\node_modules\\nedb\\lib\\datastore.js:402:10)\n' +
    '    at Datastore._insert (C:\\Users\\username\\AppData\\Local\\firebotv5\\app-5.57.0\\resources\\app.asar\\node_modules\\nedb\\lib\\datastore.js:348:10)\n' +
    '    at C:\\Users\\username\\AppData\\Local\\firebotv5\\app-5.57.0\\resources\\app.asar\\node_modules\\nedb\\lib\\executor.js:40:13\n' +
    '    at Immediate.process [as _onImmediate] (C:\\Users\\username\\AppData\\Local\\firebotv5\\app-5.57.0\\resources\\app.asar\\node_modules\\nedb\\node_modules\\async\\lib\\async.js:731:21)\n' +
    '    at processImmediate (internal/timers.js:461:21)',
  key: '409993989',
  errorType: 'uniqueViolated'
}
``` 

### Expected Behavior

firebot to update the existing user

### Version

5.57.0

### What operating system are you using Firebot on?

Windows 10

**Comment by zunderscore** [comment]
So much of what we do in v5 is tied to username vs user ID. This may be far too big of an undertaking for v5, so for now, I'm marking this for v6. We already plan to make v6 user ID centric vs username anyway.
