### ISSUE TITLE
[Bug] AWS Polly TTS effects made before the update stop working

### ISSUE THREAD

**Issue by dennisrijsdijk** [crowbartools/Firebot#2244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

AWS Polly effect will fail, not speaking the TTS.

### Expected Behavior

Amazon Polly should speak out the message as normal.

### Steps To Reproduce

1. Run an effects list that has a TTS effect from before the update.
2. Notice that the TTS doesn't play

### Version

5.58.1

### What operating system are you using Firebot on?

Windows 10

### Relevant log output

```shell
2023-09-21 00:00:21.0472 - error: [v5.58.1] There was an error running effect of type aws:polly with id b31a8233-ed57-11ed-8a34-596f884a0c42 
{
  message: "Cannot read property 'filter' of undefined",
  stack: "TypeError: Cannot read property 'filter' of undefined\n" +
    '    at Object.onTriggerEvent (C:\\Users\\user\\AppData\\Local\\firebotv5a\\app-5.58.1\\resources\\app.asar\\build\\backend\\integrations\\builtin\\aws\\text-to-speech-polly-effect.js:479:47)\n' +
    '    at runMicrotasks (<anonymous>)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n' +
    '    at async Object.runEffects (C:\\Users\\user\\AppData\\Local\\firebotv5a\\app-5.58.1\\resources\\app.asar\\build\\backend\\common\\effect-runner.js:106:30)'
}
```

**Comment by zunderscore** [comment]
Resolved in v5.59.0
