### ISSUE TITLE
 [Bug] App Locks up when Switching Profiles

### ISSUE THREAD

**Issue by sikosis** [crowbartools/Firebot#2262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When closing FireApp to switch to another profile, the app will get "stuck". 3 Firebot processes running in Task Manager. Kill one of them and then FireApp opens.

### Expected Behavior

FireBot should just close and re-open.

### Steps To Reproduce

1. Select Profile
2. Asked to close app to switch.
3. Hung

### Version

5.58.1

### What operating system are you using Firebot on?

Windows 10

### Relevant log output

```shell
2023-10-23 02:32:32.0144 - error: [v5.58.1] ViewerDB: Error adding user 
{
  message: "Can't insert key 137199626, it violates the unique constraint",
  stack: "Error: Can't insert key 137199626, it violates the unique constraint\n" +
    '    at _AVLTree.insert (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\binary-search-tree\\lib\\avltree.js:273:19)\n' +
    '    at AVLTree.insert (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\binary-search-tree\\lib\\avltree.js:307:27)\n' +
    '    at Index.insert (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\indexes.js:77:15)\n' +
    '    at Datastore.addToIndexes (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\datastore.js:180:29)\n' +
    '    at Datastore._insertInCache (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\datastore.js:402:10)\n' +
    '    at Datastore._insert (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\datastore.js:348:10)\n' +
    '    at C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\executor.js:40:13\n' +
    '    at Immediate.process [as _onImmediate] (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\node_modules\\async\\lib\\async.js:731:21)\n' +
    '    at processImmediate (internal/timers.js:461:21)',
  key: '137199626',
  errorType: 'uniqueViolated'
}
2023-10-23 02:37:31.0967 - error: [v5.58.1] ViewerDB: Error adding user 
{
  message: "Can't insert key 137199626, it violates the unique constraint",
  stack: "Error: Can't insert key 137199626, it violates the unique constraint\n" +
    '    at _AVLTree.insert (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\binary-search-tree\\lib\\avltree.js:273:19)\n' +
    '    at AVLTree.insert (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\binary-search-tree\\lib\\avltree.js:307:27)\n' +
    '    at Index.insert (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\indexes.js:77:15)\n' +
    '    at Datastore.addToIndexes (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\datastore.js:180:29)\n' +
    '    at Datastore._insertInCache (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\datastore.js:402:10)\n' +
    '    at Datastore._insert (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\datastore.js:348:10)\n' +
    '    at C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\executor.js:40:13\n' +
    '    at Immediate.process [as _onImmediate] (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\node_modules\\async\\lib\\async.js:731:21)\n' +
    '    at processImmediate (internal/timers.js:461:21)',
  key: '137199626',
  errorType: 'uniqueViolated'
}
2023-10-23 02:42:31.0964 - error: [v5.58.1] ViewerDB: Error adding user 
{
  message: "Can't insert key 137199626, it violates the unique constraint",
  stack: "Error: Can't insert key 137199626, it violates the unique constraint\n" +
    '    at _AVLTree.insert (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\binary-search-tree\\lib\\avltree.js:273:19)\n' +
    '    at AVLTree.insert (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\binary-search-tree\\lib\\avltree.js:307:27)\n' +
    '    at Index.insert (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\indexes.js:77:15)\n' +
    '    at Datastore.addToIndexes (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\datastore.js:180:29)\n' +
    '    at Datastore._insertInCache (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\datastore.js:402:10)\n' +
    '    at Datastore._insert (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\datastore.js:348:10)\n' +
    '    at C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\executor.js:40:13\n' +
    '    at Immediate.process [as _onImmediate] (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\node_modules\\async\\lib\\async.js:731:21)\n' +
    '    at processImmediate (internal/timers.js:461:21)',
  key: '137199626',
  errorType: 'uniqueViolated'
}
2023-10-23 02:47:32.0019 - error: [v5.58.1] ViewerDB: Error adding user 
{
  message: "Can't insert key 137199626, it violates the unique constraint",
  stack: "Error: Can't insert key 137199626, it violates the unique constraint\n" +
    '    at _AVLTree.insert (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\binary-search-tree\\lib\\avltree.js:273:19)\n' +
    '    at AVLTree.insert (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\binary-search-tree\\lib\\avltree.js:307:27)\n' +
    '    at Index.insert (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\indexes.js:77:15)\n' +
    '    at Datastore.addToIndexes (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\datastore.js:180:29)\n' +
    '    at Datastore._insertInCache (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\datastore.js:402:10)\n' +
    '    at Datastore._insert (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\datastore.js:348:10)\n' +
    '    at C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\executor.js:40:13\n' +
    '    at Immediate.process [as _onImmediate] (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\node_modules\\async\\lib\\async.js:731:21)\n' +
    '    at processImmediate (internal/timers.js:461:21)',
  key: '137199626',
  errorType: 'uniqueViolated'
}
2023-10-23 02:52:32.0040 - error: [v5.58.1] ViewerDB: Error adding user 
{
  message: "Can't insert key 137199626, it violates the unique constraint",
  stack: "Error: Can't insert key 137199626, it violates the unique constraint\n" +
    '    at _AVLTree.insert (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\binary-search-tree\\lib\\avltree.js:273:19)\n' +
    '    at AVLTree.insert (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\binary-search-tree\\lib\\avltree.js:307:27)\n' +
    '    at Index.insert (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\indexes.js:77:15)\n' +
    '    at Datastore.addToIndexes (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\datastore.js:180:29)\n' +
    '    at Datastore._insertInCache (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\datastore.js:402:10)\n' +
    '    at Datastore._insert (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\datastore.js:348:10)\n' +
    '    at C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\executor.js:40:13\n' +
    '    at Immediate.process [as _onImmediate] (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\node_modules\\async\\lib\\async.js:731:21)\n' +
    '    at processImmediate (internal/timers.js:461:21)',
  key: '137199626',
  errorType: 'uniqueViolated'
}
2023-10-23 02:57:31.0990 - error: [v5.58.1] ViewerDB: Error adding user 
{
  message: "Can't insert key 137199626, it violates the unique constraint",
  stack: "Error: Can't insert key 137199626, it violates the unique constraint\n" +
    '    at _AVLTree.insert (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\binary-search-tree\\lib\\avltree.js:273:19)\n' +
    '    at AVLTree.insert (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\binary-search-tree\\lib\\avltree.js:307:27)\n' +
    '    at Index.insert (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\indexes.js:77:15)\n' +
    '    at Datastore.addToIndexes (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\datastore.js:180:29)\n' +
    '    at Datastore._insertInCache (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\datastore.js:402:10)\n' +
    '    at Datastore._insert (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\datastore.js:348:10)\n' +
    '    at C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\executor.js:40:13\n' +
    '    at Immediate.process [as _onImmediate] (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\node_modules\\async\\lib\\async.js:731:21)\n' +
    '    at processImmediate (internal/timers.js:461:21)',
  key: '137199626',
  errorType: 'uniqueViolated'
}
2023-10-23 03:02:31.0988 - error: [v5.58.1] ViewerDB: Error adding user 
{
  message: "Can't insert key 137199626, it violates the unique constraint",
  stack: "Error: Can't insert key 137199626, it violates the unique constraint\n" +
    '    at _AVLTree.insert (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\binary-search-tree\\lib\\avltree.js:273:19)\n' +
    '    at AVLTree.insert (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\binary-search-tree\\lib\\avltree.js:307:27)\n' +
    '    at Index.insert (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\indexes.js:77:15)\n' +
    '    at Datastore.addToIndexes (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\datastore.js:180:29)\n' +
    '    at Datastore._insertInCache (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\datastore.js:402:10)\n' +
    '    at Datastore._insert (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\datastore.js:348:10)\n' +
    '    at C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\lib\\executor.js:40:13\n' +
    '    at Immediate.process [as _onImmediate] (C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\node_modules\\nedb\\node_modules\\async\\lib\\async.js:731:21)\n' +
    '    at processImmediate (internal/timers.js:461:21)',
  key: '137199626',
  errorType: 'uniqueViolated'
}
2023-10-23 03:04:13.0823 - info: [v5.58.1] Logging in to profile #Main Profile. Restarting now.
2023-10-23 03:04:14.0401 - info: [v5.58.1] Starting Firebot...
2023-10-23 03:28:37.0261 - error: [v5.58.1] Failed to load splash screen 
{
  message: "ERR_FAILED (-2) loading 'file:///C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\build\\gui\\splashscreen\\splash.html'",
  stack: "Error: ERR_FAILED (-2) loading 'file:///C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\build\\gui\\splashscreen\\splash.html'\n" +
    '    at rejectAndCleanup (electron/js2c/browser_init.js:217:1457)\n' +
    '    at Object.stopLoadingListener (electron/js2c/browser_init.js:217:1832)\n' +
    '    at Object.emit (events.js:315:20)',
  errno: -2,
  code: 'ERR_FAILED',
  url: 'file:///C:\\Users\\obs\\AppData\\Local\\firebotv5\\app-5.58.1\\resources\\app.asar\\build\\gui\\splashscreen\\splash.html'
}
2023-10-23 03:28:37.0262 - info: [v5.58.1] Ensuring required data folders exist...
2023-10-23 03:28:37.0267 - info: [v5.58.1] Finished verifying required folders exist.
2023-10-23 03:28:37.0335 - info: [v5.58.1] Setting logged in user cache.
2023-10-23 03:28:37.0727 - info: [v5.58.1] Finished setting up Twitch API client
2023-10-23 03:28:37.0923 - info: [v5.58.1] Updated Command cache.
2023-10-23 03:28:38.0098 - info: [v5.58.1] Starting scheduled task manager...
2023-10-23 03:28:38.0100 - info: [v5.58.1] Found 23 scheduled task(s)
2023-10-23 03:28:38.0134 - info: [v5.58.1] Scheduled task manager started
2023-10-23 03:28:40.0176 - info: [v5.58.1] Starting OBS Control...
2023-10-23 03:28:40.0861 - info: [v5.58.1] Attempting to setup chat moderation worker...
2023-10-23 03:28:40.0863 - info: [v5.58.1] Finished setting up chat moderation worker.
2023-10-23 03:28:40.0899 - info: [v5.58.1] Updated Hotkeys cache.
2023-10-23 03:28:40.0902 - info: [v5.58.1] Creating or connecting user database
2023-10-23 03:28:40.0902 - info: [v5.58.1] ViewerDB: Trying to connect to user database...
2023-10-23 03:28:40.0904 - info: [v5.58.1] ViewerDB: User Database Loaded:  C:\Users\obs\AppData\Roaming\Firebot\v5\profiles\Main Profile\db\users.db
2023-10-23 03:28:40.0904 - info: [v5.58.1] Creating or connecting stats database
2023-10-23 03:28:40.0907 - info: [v5.58.1] Creating or connecting quotes database
2023-10-23 03:28:40.0910 - info: [v5.58.1] Doing once a day backup
2023-10-23 03:28:40.0910 - info: [v5.58.1] Backup manualActivation: false
2023-10-23 03:28:40.0981 - info: [v5.58.1] Ignoring overlay-resources folder
2023-10-23 03:28:41.0002 - info: [v5.58.1] Default web server started, listening on port 7472
2023-10-23 03:28:41.0033 - info: [v5.58.1] Successfully connected to OBS.
2023-10-23 03:28:41.0273 - info: [v5.58.1] deleting old backup: backup_1696795945858_v5.58.1.zip
2023-10-23 03:28:45.0473 - info: [v5.58.1] got 'get all cmd defs' request
2023-10-23 03:28:45.0477 - info: [v5.58.1] Updated Command cache.
2023-10-23 03:28:45.0477 - info: [v5.58.1] got 'get all integrations' request
2023-10-23 03:28:45.0211 - info: [v5.58.1] Setting logged in user cache.
2023-10-23 03:28:57.0485 - info: [v5.58.1] Attempting to connect to StreamElements...
2023-10-23 03:28:58.0484 - info: [v5.58.1] Successfully connected to streamelements
2023-10-23 03:28:58.0666 - info: [v5.58.1] Connecting to Twitch PubSub...
2023-10-23 03:28:58.0667 - info: [v5.58.1] Connected to the Twitch PubSub!
2023-10-23 03:29:00.0577 - error: [v5.58.1] Failed to get channel BTTV emotes: Request failed with status code 404
```

**Comment by zunderscore** [comment]
Checking to see if this is still occurring on v5.59.2. If not, I'll close this issue.

**Comment by zunderscore** [comment]
Closing this as resolved for now. If this is still an issue, please reopen this issue or create an issue thread in Discord.
