### ISSUE TITLE
[Bug] Adding new quick actions 

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#2507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior
from a new profile
adding new quick actions removes the last 2 buttons and the new button 

changing tabs readds the missing button
this was fixed with #2401 but has returned 

### Expected Behavior

when adding a new quick action button it should show the new button that was added

### Steps To Reproduce

add a new quick action

### Version

5.62.1

### What operating system are you using Firebot on?

Windows 10

**Comment by CKY-** [comment]
@dennisrijsdijk

**Comment by dennisrijsdijk** [comment]
I believe an appropriate fix here would be to check the quick actions sorting database on startup. If any custom or system quick actions are missing, append them on the end of sorting.

**Comment by CKY-** [comment]
```ERROR (Renderer) TypeError: Cannot read properties of undefined (reading 'position')
    at $ctrl.sortQuickActions [as get] (file:///F:/fork-firebot/Firebot/Firebot/build/gui/app/directives/chat/quick-actions/quick-actions.js:100:46)
    at F:\fork-firebot\Firebot\Firebot\node_modules\angular\angular.js:24021:46
    at Array.map (<anonymous>)
    at getComparisonObject (F:\fork-firebot\Firebot\Firebot\node_modules\angular\angular.js:24020:37)
    at Array.map (<anonymous>)
    at F:\fork-firebot\Firebot\Firebot\node_modules\angular\angular.js:24007:45
    at fn (eval at compile (F:\fork-firebot\Firebot\Firebot\node_modules\angular\angular.js:16548:15), <anonymous>:4:412)
    at interceptedExpression (F:\fork-firebot\Firebot\Firebot\node_modules\angular\angular.js:17682:55)
    at Scope.$digest (F:\fork-firebot\Firebot\Firebot\node_modules\angular\angular.js:19262:34)
    at Scope.$apply (F:\fork-firebot\Firebot\Firebot\node_modules\angular\angular.js:19630:24)```
