### ISSUE TITLE
[Bug] Update Channel Rewards based Sort Tags not working

### ISSUE THREAD

**Issue by arblane** [crowbartools/Firebot#2861]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Updating the Channel Reward Pause state is not peforming as expected.

### Expected Behavior

Channel Rewards with tag 'SFX' should be updated with the set value of Pause/UnPaused.

### Steps To Reproduce

1. Create or use existing Channel Reward.
2. Add a tag, 'SFX' for example.
3. Create Preset Effect (PSE) that Updates Channel Reward by Sort Tag ('SFX') and Update Paused value is set to 'Pause'.
4. Save and Test PSE

### Version

5.63.2 and firebot-v5.63.2-nightly.24.10.03

### What operating system are you using Firebot on?

Windows 11

### Relevant log output

```shell
[2024-10-16 18:23:47.0036] - info: [v5.63.2] DBG: [Oct 16th 2024 2:23 pm] Toggle CPR - Disabled
[2024-10-16 18:23:47.0040] - error: [v5.63.2] Unhandled promise rejection 
{
  message: "Cannot read properties of undefined (reading 'includes')",
  stack: "TypeError: Cannot read properties of undefined (reading 'includes')\n" +
    '    at C:\\Users\\muskr\\AppData\\Local\\firebot\\app-5.63.2\\resources\\app.asar\\build\\backend\\effects\\builtin\\update-channel-reward.js:271:47\n' +
    '    at Array.filter (<anonymous>)\n' +
    '    at Object.onTriggerEvent (C:\\Users\\muskr\\AppData\\Local\\firebot\\app-5.63.2\\resources\\app.asar\\build\\backend\\effects\\builtin\\update-channel-reward.js:271:14)\n' +
    '    at C:\\Users\\muskr\\AppData\\Local\\firebot\\app-5.63.2\\resources\\app.asar\\build\\backend\\common\\effect-runner.js:89:40\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at triggerEffect (C:\\Users\\muskr\\AppData\\Local\\firebot\\app-5.63.2\\resources\\app.asar\\build\\backend\\common\\effect-runner.js:68:12)\n' +
    '    at C:\\Users\\muskr\\AppData\\Local\\firebot\\app-5.63.2\\resources\\app.asar\\build\\backend\\common\\effect-runner.js:147:40'
}
```

### Contact Details (Optional)

arblane

**Comment by arblane** [comment]
The same behavior appears to be occurring for Disable/Enable updates.

**Comment by arblane** [comment]
![image](https://github.com/user-attachments/assets/6627a577-0e41-4d08-b154-46b3cd7203f6)

**Comment by arblane** [comment]
![image](https://github.com/user-attachments/assets/f4007d20-7071-464c-88be-c7c1e3c9d412)

**Comment by arblane** [comment]
Changed Hydrate and Posture Check tags from 'SFX' to 'CPR' for testing, to avoid collision with unmanaged shared tag with Quack. Same result of not updating Channel Reward and logged unhandled promise rejection.
